from utils.init_state import gen_nbrs, repair_sequence_logic
from utils.topology import decode_and_synthesize, synthesize_route, verify_circuit_logic
import numpy as np
import random
import copy
def DE_run_single_experiment(
                max_iterations ,
                rotation_cycles ,
                num_neighbors ,
                num_bits ,
                base_trajectory ,
                experiment_id ,
                encoding_table ,
                pop_matrix1 ,
                pop_matrix2 ,
                pop_matrix3 ,
                pop_matrix4 ,
                fitness_history_matrix ,
                target_output ,
                CR
            ):
    """
    Executes a single experiment using Differential Evolution (DE) to optimize reversible circuits.
    """

    # --- Step 1: Initialize the population (neighbors) from current encoding matrices ---
    nbr1, nbr2, nbr3, nbr4 = gen_nbrs(pop_matrix1, pop_matrix2, pop_matrix3, pop_matrix4,num_neighbors)
    # --- Step 2: Decode encoding matrices into actual circuit gate sequences ---        
    circuit_solutions = decode_and_synthesize(
            nbr1, nbr2, nbr3, nbr4, encoding_table, num_bits, num_neighbors, base_trajectory
        )
    # --- Step 3: Evaluate fitness (gate count) and identify the best individual ---
    # solution_metrics stores (gate_count, original_index)
    solution_metrics = [(len(sol), idx) for idx, sol in enumerate(circuit_solutions)]
    # Sort by gate count (ascending order: fewer gates = better fitness)
    sorted_metrics = sorted(solution_metrics, key=lambda x: x[0])
    # Track the best solution within the current generation (local best)
    local_best_gate_count = sorted_metrics[0][0]
    local_best_idx = sorted_metrics[0][1]
    local_best_circuit = circuit_solutions[local_best_idx]
    # Initialize global optimization variables
    current_iter = 0
    global_best_gate_count = float('inf')
    global_best_circuit = []
    # --- Step 4: Evolution Loop ---
    while current_iter < max_iterations:
        current_iter += 1
        # Perform DE operations (Mutation, Crossover, Selection)
        # Returns updated population matrices and the fitness (gate counts) of the new individuals
        nbr1,nbr2,nbr3,nbr4,new_fit = Differential_Evolution(nbr1, nbr2, nbr3, nbr4,
                                                   num_neighbors, num_bits, CR, encoding_table, 
                                                   [m[0] for m in sorted_metrics], [m[1] for m in sorted_metrics], base_trajectory)
        # --- Step 5: Update Ranking and Global Optimum ---
        # Evaluate the new generation generated by the Differential function
        solution_metrics = [(sol, idx) for idx, sol in enumerate(new_fit)]
    
        sorted_metrics = sorted(solution_metrics, key=lambda x: x[0])
        
        local_best_gate_count = sorted_metrics[0][0]
        local_best_idx = sorted_metrics[0][1]
        local_best_circuit = circuit_solutions[local_best_idx]
        
        if global_best_gate_count > local_best_gate_count:
            global_best_gate_count = local_best_gate_count
            global_best_circuit = local_best_circuit
        
        # Step 6: Integrity Verification
        # Check if the synthesized circuits fulfill the logic requirements for the target output
        # valid_count = sum(verify_circuit_logic(sol, num_bits, target_output) for sol in circuit_solutions)
        
        # if valid_count != num_neighbors:
        #     print(f"Warning: Logic verification failed for {num_neighbors - valid_count} neighbors.")

        fitness_history_matrix[experiment_id][current_iter - 1] = global_best_gate_count
    return fitness_history_matrix, global_best_gate_count, global_best_circuit




def Differential_Evolution(nbr1, nbr2, nbr3, nbr4, num_neighbors, num_bits, CR,
                           encoding_table, local_best_gate_count, local_best_idx, trajectories):
    """
    Core Differential Evolution loop. 
    Evolves the entire population by applying mutation and crossover to each individual.
    """
    # Initialize containers for the next generation of the population
    new_nbr1=[]
    new_nbr2=[]
    new_nbr3=[]
    new_nbr4=[]
    new_fit=[] # Stores the gate counts (fitness) of the new individuals

    # Iterate through each candidate solution in the population
    for i in range(num_neighbors):
        # Generate a trial vector through mutation and evaluate its fitness
        # Returns: mutated matrices (per_new_nbr) and their cost/gate count (per_new_fit)
        per_new_nbr1, per_new_nbr2, per_new_nbr3, per_new_nbr4, per_new_fit = mutation(
            nbr1, nbr2, nbr3, nbr4,
            num_bits, num_neighbors, i, CR,
            encoding_table, local_best_gate_count, local_best_idx, trajectories)
        
        # Collect the results for the next generation
        new_nbr1.append(per_new_nbr1)
        new_nbr2.append(per_new_nbr2)
        new_nbr3.append(per_new_nbr3)
        new_nbr4.append(per_new_nbr4)
        new_fit.append(per_new_fit)

    # Return the updated population and their fitness scores
    return new_nbr1, new_nbr2, new_nbr3, new_nbr4, new_fit
     
   
def mutation(nbr1, nbr2, nbr3, nbr4, num_bits, num_neighbors, index, CR,
            encoding_table, local_best_gate_count, local_best_idx, trajectories):
    
    """
    Performs the Mutation and Crossover operations of Differential Evolution.
    Specifically designed for the 4-layer discrete encoding of reversible circuits.
    """
    # --- Step 1: Mutation Scaling Factor (F) ---
    # F = 0 or 1, controlling whether the difference vector is added
    F = np.random.randint(0, 2) 
    # --- Step 2: Random Selection of Three Distinct Individuals ---
    # Ensure candidates do not include the current individual 'index'
    candidates = np.arange(num_neighbors)
    candidates = candidates[candidates != index]
    # Randomly select 3 unique indices (r1, r2, r3) 
    r_indices = np.random.choice(candidates, 3, replace=False)

    # Deep copy parents to avoid memory reference issues (Data Integrity)
    parent1_n1=copy.deepcopy(nbr1[r_indices[0]])
    parent2_n1=copy.deepcopy(nbr1[r_indices[1]])
    parent3_n1=copy.deepcopy(nbr1[r_indices[2]])

    # --- Step 3: Layer 1 Mutation
    mutated_n1=[]
    for i in range(len(parent1_n1)):
        row=[]
        for j in range(len(parent1_n1[0])):
            xor_val = parent2_n1[i][j] ^ parent3_n1[i][j]
            mutated_val = parent1_n1[i][j] | (F & xor_val)
            row.append(mutated_val)
        mutated_n1.append(row)
    mutated_n1 = np.array(mutated_n1)

    # Layer 2 Mutation
    parent1_n2=copy.deepcopy(nbr2[r_indices[0]])
    parent2_n2=copy.deepcopy(nbr2[r_indices[1]])
    parent3_n2=copy.deepcopy(nbr2[r_indices[2]])
    
    mutated_n2 = []
    for i in range(len(parent1_n2)):
        row=[]
        for j in range(len(parent1_n2[i])):
            xor_val = parent2_n2[i][j] ^ parent3_n2[i][j]
            mutated_val = parent1_n2[i][j] | (F & xor_val)
            row.append(mutated_val)
        mutated_n2.append(row)
    
    #  Layer 3 Mutation 
    parent1_n3=copy.deepcopy(nbr3[r_indices[0]])
    parent2_n3=copy.deepcopy(nbr3[r_indices[1]])
    parent3_n3=copy.deepcopy(nbr3[r_indices[2]])

    mutated_n3=[]
    for i in range(len(parent1_n3)):
        tmp_1 = []
        for j in range(len(parent1_n3[i])):
            tmp_2 = []
            for k in range(len(parent1_n3[i][j])):
                tmp_3 = []
                if parent1_n3[i][j][k]!=999:
                    for l in range(len(parent1_n3[i][j][k])):
                        xor_val=parent2_n3[i][j][k][l]^parent3_n3[i][j][k][l]
                        aand=F&xor_val
                        oor=parent1_n3[i][j][k][l]|aand
                        tmp_3.append(oor)
                    tmp_2.append(tmp_3)
                else:tmp_2.append(999)#999的另外處理
            tmp_1.append(tmp_2)
        mutated_n3.append(tmp_1)

    # Layer 4 Mutation 
    parent1_n4=copy.deepcopy(nbr4[r_indices[0]])
    parent2_n4=copy.deepcopy(nbr4[r_indices[1]])
    parent3_n4=copy.deepcopy(nbr4[r_indices[2]])

    mutated_n4 = []
    for i in range(len(parent1_n4)):
        layer = []
        for j in range(len(parent1_n4[i])):
            bit_vector = []
            for k in range(len(parent1_n4[i][j])):
                xor_val = parent2_n4[i][j][k] ^ parent3_n4[i][j][k]
                mutated_val = parent1_n4[i][j][k] | (F & xor_val)
                bit_vector.append(mutated_val)
            layer.append(bit_vector)
        mutated_n4.append(layer)
    
    # --- Step 4: Binomial Crossover (Inheritance from Mutated vs. Target) ---
    # Crossover for Layer 1
    trial_n1=[]
    for i in range(len(mutated_n1)):
        row=[]
        for j in range(len(mutated_n1[i])):
            r = random.random()
            if(r<=CR):
                row.append(mutated_n1[i][j])
            else:row.append(nbr1[index][i][j])
        trial_n1.append(row)
    trial_n1 = np.array(trial_n1)

    # Crossover for Layer 2
    trial_n2 = []
    for i in range(len(mutated_n2)):
        row = []
        for j in range(len(mutated_n2[i])):
            r = random.random()
            if( r <= CR):
                row.append(mutated_n2[i][j])
            else:row.append(nbr2[index][i][j])
        trial_n2.append(row)

    # Crossover for Layer 3
    trial_n3=[]
    for i in range(len(mutated_n3)):
        tmp_layer=[]
        for j in range(len(mutated_n3[i])):
            tmp_sub=[]
            for k in range(len(mutated_n3[i][j])):
                tmp_val=[]
                if mutated_n3[i][j][k]!=999:
                    for l in range(len(mutated_n3[i][j][k])):
                        r = random.random()
                        if(r<=CR):
                            
                            tmp_val.append(mutated_n3[i][j][k][l])
                        else:tmp_val.append(nbr3[index][i][j][k][l])
                    tmp_sub.append(tmp_val)
                else:tmp_sub.append(999)
            tmp_layer.append(tmp_sub)
        trial_n3.append(tmp_layer)


    # Crossover for Layer 4 with Sequence Repair
    trial_n4=[]
    for i in range(len(mutated_n4)):
        tmp_layer=[]
        for j in range(len(mutated_n4[i])):
            tmp_sub=[]
            for k in range(len(mutated_n4[i][j])):
                r = random.random()
                if(r<=CR):
                    tmp_sub.append(mutated_n4[i][j][k])
                else:tmp_sub.append(nbr4[index][i][j][k])
            tmp_sub=repair_sequence_logic(tmp_sub) #repair
            tmp_layer.append(tmp_sub)
            
        trial_n4.append(tmp_layer)
    
     # --- Step 5: Decoding and Fitness Evaluation ---
    # Decode binary strings to integers for Layer 1
    decoded_n1 = [int(''.join(map(str, row)), 2) for row in trial_n1]
        
    # Decode and handle modulo constraints for Layer 2
    decoded_n2=[]
    for q_idx, row in enumerate(trial_n2):
        val = int(''.join(map(str, row)), 2)
        # Apply modulo to ensure index remains within encoding table bounds
        decoded_n2.append(val % encoding_table[q_idx] if val >= encoding_table[q_idx] else val)

    # Decode Layer 3 priority weights
    decoded_n3 = []
    for layer in trial_n3:
        tmp_layer = []
        for sub_layer in layer:
            tmp_sub = []
            if sub_layer[0] != 999:
                for bit_vector in sub_layer:
                    decimal_weight = int(''.join(map(str, bit_vector)), 2)
                    tmp_sub.append(decimal_weight)
            else:
                tmp_sub.append(999)
            tmp_layer.append(tmp_sub)
        decoded_n3.append(tmp_layer)
    

    # Synthesize the circuit based on the trial individual
    synthesized_circuit=synthesize_route(decoded_n1, decoded_n2, decoded_n3,
                                         trial_n4, num_bits, trajectories) 
     
    trial_fitness=len(synthesized_circuit)
    history_idx = local_best_idx.index(index)
    target_fitness=local_best_gate_count[history_idx]

    if trial_fitness <= target_fitness:
        return trial_n1,trial_n2,trial_n3,trial_n4,trial_fitness
    else:
        # Return the original target individual if the trial individual is worse
        return (nbr1[index], nbr2[index],
    nbr3[index], nbr4[index], target_fitness)